<a href="https://colab.research.google.com/github/lovnishverma/Python-Getting-Started/blob/main/NumPy_16_Jun.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img src="https://upload.wikimedia.org/wikipedia/commons/3/31/NumPy_logo_2020.svg" width="212">

# **NumPy**

**What is NumPy?**

*NumPy is a Python library used for working with arrays.*

- It also has functions for working in domain of linear algebra, fourier transform, and matrices.

* NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

* NumPy stands for Numerical Python.

https://numpy.org/

https://www.w3schools.com/python/numpy/numpy_intro.asp

https://pypi.org/project/numpy/

In [ ]:
# check python version

import os
import sys
print(sys.version)

3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0]

In [ ]:
!python --version

Python 3.12.13

In [ ]:
# !pip install numpy -q

In [ ]:
print(np.__version__)

2.0.2

In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,3])

print(arr)

print(type(arr))

print(arr.shape)

print(arr.ndim)

print(arr.dtype)



# Total no. of elements
print(arr.size)

[1 2 3]
<class 'numpy.ndarray'>
(3,)
1
int64
3

In [ ]:
arr2d = np.array([[1,2,3], [4,5,6]])

print(arr2d)

print(type(arr2d))

print(arr2d.shape) # Rows, Columns

print(arr2d.ndim)

print(arr2d.dtype)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)
2
int64

In [ ]:
arr3d = np.array([[[1,2,3], [4,5,6], [7,8,9]]])

print(arr3d)

print(type(arr3d))

print(arr3d.shape) # Rows, Columns

print(arr3d.ndim)

print(arr3d.dtype)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
<class 'numpy.ndarray'>
(1, 3, 3)
3
int64

In [ ]:
ls = [[1,2,3], [4,5,6]]

arr = np.array(ls)

print(arr)

print(type(arr))

print(arr.shape)

print(arr.ndim)

print(arr.dtype)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)
2
int64

**Special Arrays**

In [ ]:
zeros = np.zeros((6,6))

print(zeros)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

In [ ]:
ones = np.ones((3,3))

print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

In [ ]:
eye = np.eye(3)

print(eye)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

In [ ]:
r = np.random.rand(3,3)
print(r)

[[0.64972168 0.58087723 0.16888183]
 [0.41586877 0.65300567 0.62057164]
 [0.40377004 0.87376594 0.5550648 ]]

In [ ]:
seed = np.random.seed(43)
rr = np.random.rand(3,3)
print(rr)

[[0.11505457 0.60906654 0.13339096]
 [0.24058962 0.32713906 0.85913749]
 [0.66609021 0.54116221 0.02901382]]

In [ ]:
rrr = np.random.randint(1,100,(3,3))
print(rrr)

[[51 76 90]
 [66 35 76]
 [67  5 37]]

**Array Indexing & Slicing**

In [ ]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[0])      # First element
print(arr[-1])     # Last element
print(arr[1:4])    # Slicing (from index 1 to 3)
print(arr[::2])    # Every second element

print(arr[::2]) # start:stop:jump(step)

10
50
[20 30 40]
[10 30 50]
[10 30 50]

In [ ]:
arr2d = np.array([[1, 2, 3, 4], [4, 5, 6, 7], [8,9,10,11]])

print(arr2d )

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 8  9 10 11]]

In [ ]:
print(arr2d[1,1:3])

[5 6]

In [ ]:
print(arr2d[:,: -1])  # Row, Column

[[ 1  2  3]
 [ 4  5  6]
 [ 8  9 10]]

In [ ]:
print(arr2d[0, 1])  # Row 0, Column 1
print(arr2d[:, 1])  # All rows, Column 1
print(arr2d[1, :])  # Row 1, all columns

2
[2 5 9]
[4 5 6 7]

Arithmetic Operations

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)  # Element-wise addition
print(a - b)  # Element-wise subtraction
print(a * b)  # Element-wise multiplication
print(a / b)  # Element-wise division
print(a ** 2) # Square of each element

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]

Aggregations

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

print(np.sum(arr))  # Sum of elements
print(np.mean(arr)) # Mean (average)
print(np.max(arr))  # Maximum element
print(np.min(arr))  # Minimum element
print(np.std(arr))  # Standard deviation

15
3.0
5
1
1.4142135623730951

 Reshaping & Transposing

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape(2, 3)
print(reshaped)

print(type(reshaped))

print(reshaped.shape)

print(reshaped.ndim)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)
2

In [ ]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2d.T)  # Transpose of matrix

[[1 4]
 [2 5]
 [3 6]]

In [ ]:
arr1 = np.array([1, 2, 3, 4, 5, 6])
arr2 = np.array([7, 8, 9, 10, 11, 12])
concatenated = np.concatenate((arr1, arr2))
print(concatenated)

[ 1  2  3  4  5  6  7  8  9 10 11 12]

In [ ]:
arr1 = np.array([1, 2, 3, 4, 5, 6])
arr2 = np.array([7, 8, 9, 10, 11, 12])

# Horizontal stacking

h_stack = np.hstack((arr1, arr2))
print(h_stack)

print("---------------------------------------")

# Vertical stacking
v_stack = np.vstack((arr1, arr2))
print(v_stack)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
---------------------------------------
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

**Useful Numpy fuctions**

In [ ]:
arr = np.array([1,2,3,4,4,5,6,6])

unique = np.unique(arr)
print(unique)

[1 2 3 4 5 6]

In [ ]:
arr = np.array([1,2,7,3,4,4,5,6,6])

sort = np.sort(arr)
print(sort)

[1 2 3 4 4 5 6 6 7]

In [ ]:
arr = np.array([1,2,7,3,8,4,4,5,6,6])

where_vals = np.where(arr == 6)

print(where_vals)

(array([8, 9]),)

Mini Project example: Normalization

In [ ]:
data = np.array([50, 100, 150, 200])

normalized = (data - np.min(data)) / (np.max(data) - np.min(data))

print(normalized)

[0.         0.33333333 0.66666667 1.        ]

https://numpy.org/doc/

https://numpy.org/doc/stable/user/absolute_beginners.html

https://github.com/sarwansingh/Python/blob/master/Slides/5.Numpy1.pdf

https://github.com/sarwansingh/Python/blob/master/Slides/5.Numpy2.pdf

https://github.com/lovnishverma/Python-Getting-Started/blob/main/Iris_NumPy.ipynb

https://github.com/lovnishverma/Python-Getting-Started/blob/main/30%20NumPy%20Projects%20Ideas.pdf

https://github.com/lovnishverma/Python-Getting-Started/blob/main/numpy_official.ipynb

https://github.com/lovnishverma/Python-Getting-Started/blob/main/numpy_mini_project.ipynb

https://github.com/lovnishverma/Python-Getting-Started/blob/main/numpy_vs_python_speed_demo.ipynb

# Pandas

In [ ]:
# !pip install pandas -q

In [ ]:
import pandas as pd

In [ ]:
data = {"Name": ["Lovnish", "Raju", "Puneeta", "Puneeta"],
        "Age": [np.nan, 42, 30, 30],
        "City": ["Delhi", "Mumbai", "Kolkata", "Kolkata"],
        "Country": ["India", "India", "India", "India"],
        "Salary": [50000, 60000, 55000, 55000],
        "Experience": [2, 7, 5, 5],
        "Married": [True, False, True, True],
        "Education": ["B.Tech", "M.Tech", "B.Sc", "B.Sc"],
        "Gender": ["Male", "Male", "Female", "Female"]
        }
type(data)

dict

In [ ]:
df = pd.DataFrame(data)

In [ ]:
df.dtypes

Name           object
Age           float64
City           object
Country        object
Salary          int64
Experience      int64
Married          bool
Education      object
Gender         object
dtype: object

In [ ]:
df

,Name,Age,City,Country,Salary,Experience,Married,Education,Gender
0,Lovnish,NaN,Delhi,India,50000,2,True,B.Tech,Male
1,Raju,42.0,Mumbai,India,60000,7,False,M.Tech,Male
2,Puneeta,30.0,Kolkata,India,55000,5,True,B.Sc,Female
3,Puneeta,30.0,Kolkata,India,55000,5,True,B.Sc,Female

In [ ]:
# Delete a cloumn

# df.drop(columns=['Age'], inplace=True)

In [ ]:
df

,Name,Age,City,Country,Salary,Experience,Married,Education,Gender
0,Lovnish,NaN,Delhi,India,50000,2,True,B.Tech,Male
1,Raju,42.0,Mumbai,India,60000,7,False,M.Tech,Male
2,Puneeta,30.0,Kolkata,India,55000,5,True,B.Sc,Female
3,Puneeta,30.0,Kolkata,India,55000,5,True,B.Sc,Female

In [ ]:
df['Education']

0    B.Tech
1    M.Tech
2      B.Sc
3      B.Sc
Name: Education, dtype: object

In [ ]:
df.Education

0    B.Tech
1    M.Tech
2      B.Sc
3      B.Sc
Name: Education, dtype: object

In [ ]:
df['Gender'].value_counts()

Gender
Male      2
Female    2
Name: count, dtype: int64

In [ ]:
df['Age'].mean()

np.float64(34.0)

In [ ]:
df[['Age', 'Name']]

    Age     Name
0   NaN  Lovnish
1  42.0     Raju
2  30.0  Puneeta
3  30.0  Puneeta

In [ ]:
df.describe()

             Age        Salary  Experience
count   3.000000      4.000000    4.000000
mean   34.000000  55000.000000    4.750000
std     6.928203   4082.482905    2.061553
min    30.000000  50000.000000    2.000000
25%    30.000000  53750.000000    4.250000
50%    30.000000  55000.000000    5.000000
75%    36.000000  56250.000000    5.500000
max    42.000000  60000.000000    7.000000

In [ ]:
df.duplicated()

0    False
1    False
2    False
3     True
dtype: bool

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df

,Name,Age,City,Country,Salary,Experience,Married,Education,Gender
0,Lovnish,NaN,Delhi,India,50000,2,True,B.Tech,Male
1,Raju,42.0,Mumbai,India,60000,7,False,M.Tech,Male
2,Puneeta,30.0,Kolkata,India,55000,5,True,B.Sc,Female

In [ ]:
df.isnull().sum()

Name          0
Age           1
City          0
Country       0
Salary        0
Experience    0
Married       0
Education     0
Gender        0
dtype: int64

In [ ]:
df['Age'].fillna(25, inplace=False)

0    25.0
1    42.0
2    30.0
Name: Age, dtype: float64

In [ ]:
df['Age'].fillna(df["Age"].mean(), inplace=False)

0    36.0
1    42.0
2    30.0
Name: Age, dtype: float64

In [ ]:
df

,Name,Age,City,Country,Salary,Experience,Married,Education,Gender
0,Lovnish,NaN,Delhi,India,50000,2,True,B.Tech,Male
1,Raju,42.0,Mumbai,India,60000,7,False,M.Tech,Male
2,Puneeta,30.0,Kolkata,India,55000,5,True,B.Sc,Female

In [ ]:
df.dropna(inplace=True)

In [ ]:
df

,Name,Age,City,Country,Salary,Experience,Married,Education,Gender
1,Raju,42.0,Mumbai,India,60000,7,False,M.Tech,Male
2,Puneeta,30.0,Kolkata,India,55000,5,True,B.Sc,Female

In [ ]:
# Save csv

df.to_csv("mydata.csv", index=False)

https://github.com/lovnishverma/Python-Getting-Started/blob/main/Importing_Datasets_in_Google_Colab_using_pandas.ipynb

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/lovnishverma/datasets/refs/heads/main/Salaries.csv")

In [ ]:
df.head()

   rank discipline  phd  service   sex  salary
0  Prof          B   56       49  Male  186960
1  Prof          A   12        6  Male   93000
2  Prof          A   23       20  Male  110515
3  Prof          A   40       31  Male  131205
4  Prof          B   20       18  Male  104800

https://github.com/lovnishverma/Python-Getting-Started/blob/main/%F0%9F%90%BC_Python_Pandas.ipynb